### PR TITLE
R2 Feature Release

### PR DESCRIPTION
**Pull request by kalvinwang**
## Release

- R2 Feature Release
- Merges `future` into `main`

## Changelog

Major features:
- Adds Global Header
- Adds BYE (benefit year end) scenarios
- Adds support for new API gateway field `hasValidPendingWeeks` 
  - `hasPendingWeeks` will be deprecated in a future release

View the [changelog of 17 PRs](https://github.com/cagov/ui-claim-tracker/pulls?q=is%3Apr+merged%3A2021-09-03T12%3A07%3A00-07%3A00..2021-12-02+base%3Afuture+) in this release using:
```
is:pr merged:2021-09-03T12:07:00-07:00..2021-12-02 base:future 
```

### CODE REVIEW

**Comment by rocketnova** [comment]
I suggest updating the description for this PR for easier future reference to something like this:

## Release

- R2 Feature Release
- Merges `future` into `main`

## Changelog

Major features:
- Adds Global Header
- Adds BYE (benefit year end) scenarios

View the [changelog of 17 PRs](https://github.com/cagov/ui-claim-tracker/pulls?q=is%3Apr+merged%3A2021-09-03T12%3A07%3A00-07%3A00..2021-12-02+base%3Afuture+) in this release using:
```
is:pr merged:2021-09-03T12:07:00-07:00..2021-12-02 base:future 
```

**Comment by kalvinwang** [comment]
@rocketnova wonderful, thank you! I think I'll replace the existing line `git log --first-parent --oneline main..future to generate the changelog for the merge description` with a link to this PR as an example instead, does that sound good to you or was that existing line meant for another purpose?

**Review by rocketnova — APPROVED** [review]
I reviewed all the changes and they generally all look like changes I've seen before in one of our other PRs. Lots of work here!

**Comment by rocketnova** [comment]
> @rocketnova wonderful, thank you! Also I think I'll replace the existing line in our release process doc `git log --first-parent --oneline main..future to generate the changelog for the merge description` with a link to this PR as an example for the description instead, does that sound good to you or was that existing line meant for another purpose?

Sure, that sounds good. 

In reviewing the file changes, I remembered that this release will also include the API field changes, so I updated the description with that.

**Pull request merged**
