### PR TITLE
Removes the unused Loading logic

### LINKED ISSUE #231: Remove Loading functionality from Components
### Description

_If we decide not to implement #230_ we should remove the loading functionality from the presentation components as dead code.

If we do implement #230, this ticket can be closed.

### Acceptance Criteria

- [ ]  `loading` prop is removed from the components (trace starting from [index.tsx](https://github.com/cagov/ui-claim-tracker/blob/main/pages/index.tsx))
- [ ] Components that conditionally load Shimmer components when `loading=true` just return themselves unconditionally.
- [ ] `Shimmer` & `ShimmeField` components, their stories, and styling are removed.
- [ ] `Main` storybook's loading story is removed.

### PR DESCRIPTION
**Pull request by lomky**
===

Resolves #231 

- [x] Loading functionality is removed from code, stories, and tests
- [x] Storybook still loads
- [x] App is visually & functionally unaffected outside of loading

### CODE REVIEW

**Review by rocketnova — COMMENTED** [review]
Do we also need to remove the `shimmer` dependency?

**Comment by lomky** [comment]
> Do we also need to remove the shimmer dependency?

**Comment by lomky** [comment]
> Do we also need to remove the shimmer dependency?

I tried - something else pulls it in!

**Comment by rocketnova** [comment]
> > Do we also need to remove the shimmer dependency?
> 
> I tried - something else pulls it in!

Got it!

**Review by rocketnova — APPROVED** [review]
LGTM!

**Pull request merged**
